/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'brand-blue': '#19ADFA',
        'brand-yellow': '#F2BE3C',
        'brand-text': '#333333',
        'brand-bg': '#F8F8F8',
        primary: '#002de6',
        'secondary-fixed-dim': '#e9c400',
        'surface-bright': '#f8f9fa',
        'on-primary-fixed-variant': '#0029d3',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        'surface-container-low': '#f3f4f5',
        'on-primary-fixed': '#000d60',
        'on-tertiary-fixed-variant': '#891e00',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e1e3e4',
        'on-tertiary-fixed': '#3c0800',
        'primary-fixed-dim': '#bcc3ff',
        outline: '#737688',
        'surface-dim': '#d9dadb',
        'outline-variant': '#c3c5d9',
        'tertiary-fixed': '#ffdbd2',
        'surface-container': '#edeeef',
        secondary: '#705d00',
        'tertiary-fixed-dim': '#ffb4a1',
        'on-primary-container': '#e1e3ff',
        'inverse-primary': '#bcc3ff',
        surface: '#f8f9fa',
        'on-background': '#191c1d',
        'on-error': '#ffffff',
        'inverse-surface': '#2e3132',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#ffe170',
        tertiary: '#952200',
        'on-tertiary-container': '#ffddd5',
        'on-surface-variant': '#434656',
        'surface-variant': '#e1e3e4',
        'on-secondary-fixed': '#221b00',
        'surface-container-high': '#e7e8e9',
        'tertiary-container': '#bf3003',
        'primary-container': '#314eff',
        'on-secondary-fixed-variant': '#544600',
        'inverse-on-surface': '#f0f1f2',
        'on-secondary-container': '#6f5c00',
        background: '#f8f9fa',
        'on-surface': '#191c1d',
        'on-primary': '#ffffff',
        'primary-fixed': '#dfe0ff',
        'surface-tint': '#1f41ff',
        'secondary-container': '#fdd400',
      },
      fontFamily: {
        heading: ['Montserrat', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['"Open Sans"', 'system-ui', 'sans-serif'],
        manrope: ['Manrope', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'soft-lg': '0 18px 45px rgba(0,0,0,0.08)',
      },
      borderRadius: {
        '2xl': '1.25rem',
        '3xl': '1.75rem',
      },
    },
  },
  plugins: [],
};
